### ISSUE TITLE
Jackson annotations library compatibility issue

### ISSUE THREAD

**Issue by priyank5485** [hortonworks/streamline#1019]
When one creates a SAM application with a Kafka source and a Rules processor and then try to deploy it, they might run in to an exception as below depending on the classpath supplied to storm jar deployment command. It seems to be due to an older version of jackson annotations library being the class path.

1030 [main] WARN  o.a.s.f.FluxBuilder - Found multiple invokable methods for class class org.apache.storm.kafka.spout.KafkaSpoutConfig$Builder, method setProp, given arguments [{security.protocol=SASL_PLAINTEXT, max.poll.records=500, value.deserializer=org.apache.kafka.common.serialization.ByteBufferDeserializer, sasl.kerberos.service.name=kafka, group.id=1, ssl.truststore.type=JKS, max.partition.fetch.bytes=1048576, ssl.keystore.type=JKS, sasl.jaas.config=com.sun.security.auth.module.Krb5LoginModule required useKeyTab=true storeKey=true keyTab="/etc/security/keytabs/hcube.headless.keytab"  principal="hcube@HWX.COMPANY";, ssl.keymanager.algorithm=SunX509, ssl.trustmanager.algorithm=PKIX, key.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer, ssl.protocol=TLS, fetch.min.bytes=1}]. Using the last one found.
1031 [main] INFO  o.a.s.f.FluxBuilder - Detected DSL topology...
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.storm.flux.FluxBuilder.buildObject(FluxBuilder.java:310)
	at org.apache.storm.flux.FluxBuilder.buildBolts(FluxBuilder.java:391)
	at org.apache.storm.flux.FluxBuilder.buildTopology(FluxBuilder.java:87)
	at org.apache.storm.flux.Flux.runCli(Flux.java:153)
	at org.apache.storm.flux.Flux.main(Flux.java:98)
Caused by: java.lang.NoSuchFieldError: USE_DEFAULTS
	at com.fasterxml.jackson.annotation.JsonInclude$Value.<clinit>(JsonInclude.java:205)
	at com.fasterxml.jackson.streamline.databind.cfg.MapperConfig.<clinit>(MapperConfig.java:45)
	at com.fasterxml.jackson.streamline.databind.ObjectMapper.<init>(ObjectMapper.java:535)
	at com.fasterxml.jackson.streamline.databind.ObjectMapper.<init>(ObjectMapper.java:452)
	at com.hortonworks.streamline.common.util.Utils.createObjectFromJson(Utils.java:147)
	at com.hortonworks.streamline.streams.runtime.storm.bolt.rules.RulesBolt.<init>(RulesBolt.java:59)
	... 9 more
 
ERROR  [17:42:58.314] [ForkJoinPool-4-worker-2] c.h.s.s.a.t.s.TopologyStates -  Error while trying to deploy the topology in the streaming engine 
java.lang.Exception: Topology could not be deployed successfully: storm deploy command failed with Exception in thread "main" java.lang.reflect.InvocationTargetException
	at com.hortonworks.streamline.streams.actions.storm.topology.StormTopologyActionsImpl.deploy(StormTopologyActionsImpl.java:254)
	at com.hortonworks.streamline.streams.actions.topology.state.TopologyStates$5.deploy(TopologyStates.java:122)
	at com.hortonworks.streamline.streams.actions.topology.state.TopologyContext.deploy(TopologyContext.java:87)
	at com.hortonworks.streamline.streams.actions.topology.service.TopologyActionsService.deployTopology(TopologyActionsService.java:116)
	at com.hortonworks.streamline.streams.service.TopologyCatalogResource.lambda$deploy$3(TopologyCatalogResource.java:519)
	at com.hortonworks.streamline.common.util.ParallelStreamUtil.lambda$runAsync$0(ParallelStreamUtil.java:56)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
ERROR  [17:42:58.314] [ForkJoinPool-4-worker-2] c.h.s.s.a.t.s.TopologyStates -  Trying to kill any running instance of topology 'Test' 
ERROR  [17:42:58.398] [ForkJoinPool-4-worker-2] c.h.s.c.u.ParallelStreamUtil -  Got exception while running async task 
java.lang.RuntimeException: java.lang.Exception: Topology could not be deployed successfully: storm deploy command failed with Exception in thread "main" java.lang.reflect.InvocationTargetException
	at com.hortonworks.streamline.common.util.ParallelStreamUtil.lambda$runAsync$0(ParallelStreamUtil.java:58)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.Exception: Topology could not be deployed successfully: storm deploy command failed with Exception in thread "main" java.lang.reflect.InvocationTargetException
	at com.hortonworks.streamline.streams.actions.storm.topology.StormTopologyActionsImpl.deploy(StormTopologyActionsImpl.java:254)
	at com.hortonworks.streamline.streams.actions.topology.state.TopologyStates$5.deploy(TopologyStates.java:122)
	at com.hortonworks.streamline.streams.actions.topology.state.TopologyContext.deploy(TopologyContext.java:87)
	at com.hortonworks.streamline.streams.actions.topology.service.TopologyActionsService.deployTopology(TopologyActionsService.java:116)
	at com.hortonworks.streamline.streams.service.TopologyCatalogResource.lambda$deploy$3(TopologyCatalogResource.java:519)
	at com.hortonworks.streamline.common.util.ParallelStreamUtil.lambda$runAsync$0(ParallelStreamUtil.java:56)

**Comment by satishd** [comment]
#1020
