### ISSUE TITLE
Test mode throws IllegalStateException

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#1069]
Topology details : http://hdf-3-1-build3.field.hortonworks.com:7777/#/applications/4/edit?_k=membfo

It throws an exception when trying to view any of the events by clicking on the bottom panel.

The stacktrace is below:

```
ERROR  [20:49:31.883] [dw-62453 - GET /api/v1/catalog/topologies/4/testhistories/55/events/correlated/bc9ba583-54a3-4f81-8cd2-b0511627a673] c.h.s.s.s.TopologyTestRunResource -  Got exception: [IllegalStateException] / message [Duplicate key EventInformation{timestamp=1512679550726, componentName='Split', streamId='projection_transform_stream_47', targetComponentName='ENRICH-WEATHER', eventId='563faea7-3335-4c9c-bca8-3c29ada88aba', rootIds=[bc9ba583-54a3-4f81-8cd2-b0511627a673, 037a8e52-62b8-4c2b-b82e-d10f3006fe40], parentIds=[52fa7470-ae64-4537-9dc7-3b03d0046c47], fieldsAndValues={splitJoinValue=1506437672640, week=39, eventTime=2017-09-26 14:54:32.64, eventSource=truck_geo_event, truckId=54, driverId=23, driverName=Jeff Markham, routeId=1, route=Peoria to Ceder Rapids Route 2, eventType=Normal, latitude=40.7, longitude=-89.52, correlationId=1, geoAddress=, speed=58}}] / related resource location: [com.hortonworks.streamline.streams.service.TopologyTestRunResource.getGroupedCorrelatedEventsOfTestRunTopologyHistory](TopologyTestRunResource.java:261)
java.lang.IllegalStateException: Duplicate key EventInformation{timestamp=1512679550726, componentName='Split', streamId='projection_transform_stream_47', targetComponentName='ENRICH-WEATHER', eventId='563faea7-3335-4c9c-bca8-3c29ada88aba', rootIds=[bc9ba583-54a3-4f81-8cd2-b0511627a673, 037a8e52-62b8-4c2b-b82e-d10f3006fe40], parentIds=[52fa7470-ae64-4537-9dc7-3b03d0046c47], fieldsAndValues={splitJoinValue=1506437672640, week=39, eventTime=2017-09-26 14:54:32.64, eventSource=truck_geo_event, truckId=54, driverId=23, driverName=Jeff Markham, routeId=1, route=Peoria to Ceder Rapids Route 2, eventType=Normal, latitude=40.7, longitude=-89.52, correlationId=1, geoAddress=, speed=58}}
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
	at java.util.HashMap.merge(HashMap.java:1253)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.hortonworks.streamline.streams.common.event.correlation.CorrelatedEventsGrouper.groupByComponent(CorrelatedEventsGrouper.java:34)
	at com.hortonworks.streamline.streams.service.TopologyTestRunResource.getGroupedCorrelatedEventsOfTestRunTopologyHistory(TopologyTestRunResource.java:261)
	at sun.reflect.GeneratedMethodAccessor499.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:34)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:50)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:44)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240)
	at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:459)
	at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:68)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by HeartSaVioR** [comment]
@arunmahadevan 
I missed one event being fanning out to multiple downstream components. I was expecting output streams are different and so different events with same content will be emitted even fanning-out, but unfortunately split processor uses same stream for fanning out.

I didn't see the case in Streamline, but it is still possible for component to emit an event to a component with fanning out to multiple tasks.

There looks like two approaches:

1. Not allowing using same stream across edges: if Split processor fans out an event to 5 downstream processors, create 5 streams. It can't handle 1:1 emit with fanning out grouping, but easier to address, and don't need runner specific fix.

2. Hack output collector to create event for each output task (only it has multiple target tasks) when emitting. The detail will be behind on hacked code which is bad, but can resolve both of cases. If Streamline bothers about event ID only for event correlation, this approach should be OK because using wrapped output collector is the only way to track event correlation so we won't miss it.

**Comment by HeartSaVioR** [comment]
Just realized that approach 2 is not possible cause whatever we do from wrapped output collector (unless we don't delegate the emit logic), delegated output collector will emit a tuple to multiple destinations. Maybe we need to live with duplicated events, then need to revisit the logic.

**Comment by arunmahadevan** [comment]
Duplicated events because the same event is received by multiple targets ? I think it may be ok to display the same event in each target, but need to avoid the IllegalStateException.

**Comment by arunmahadevan** [comment]
Thanks @HeartSaVioR for taking care of this. Merged https://github.com/hortonworks/streamline/pull/1072 to master
