### ISSUE TITLE
Exception while querying kafka offset metrics

### ISSUE THREAD

**Issue by omkreddy** [hortonworks/streamline#1117]
```
GET /api/v1/metrics/topologies/7/components/13/kafka_topic_offsets?from=1514358550179&to=1514444950179] c.h.s.s.s.Met
ricsResource -  Got exception: [IllegalStateException] / message [Failed to parse topology configuration.] / related resource location: [com.hortonwork
s.streamline.streams.service.MetricsResource.getKafkaTopicOffsets](MetricsResource.java:221)
java.lang.IllegalStateException: Failed to parse topology configuration.
        at com.hortonworks.streamline.streams.metrics.storm.topology.StormTopologyTimeSeriesMetricsImpl.findKafkaTopicName(StormTopologyTimeSeriesMetri
csImpl.java:184)
        at com.hortonworks.streamline.streams.metrics.storm.topology.StormTopologyTimeSeriesMetricsImpl.getkafkaTopicOffsets(StormTopologyTimeSeriesMet
ricsImpl.java:86)
        at com.hortonworks.streamline.streams.metrics.storm.topology.StormTopologyMetricsImpl.getkafkaTopicOffsets(StormTopologyMetricsImpl.java:244)
        
http://ctr-e136-1513029738776-24478-01-000003.hwx.site:6188/ws/v1/timeline/metrics?appId=nimbus&hostname=&metricNames=topology.streamline-1-testapp.kafka-topic.yelpreview.totalSpoutLag&startTime=1514456772456&endTime=1514457772456&seriesAggregateFunction=AVG
 
 	ERROR  [14:55:47.229] [dw-283 - GET /api/v1/metrics/topologies/1/components/1/kafka_topic_offsets?from=1514471116927&to=1514472126927] c.h.s.s.s.Metric
sResource -  Got exception: [IllegalStateException] / message [Failed to parse topology configuration.] / related resource location: [com.hortonworks.s
treamline.streams.service.MetricsResource.getKafkaTopicOffsets](MetricsResource.java:221)
java.lang.IllegalStateException: Failed to parse topology configuration.
        at com.hortonworks.streamline.streams.metrics.storm.topology.StormTopologyTimeSeriesMetricsImpl.findKafkaTopicName(StormTopologyTimeSeriesMetri
csImpl.java:184)
        at com.hortonworks.streamline.streams.metrics.storm.topology.StormTopologyTimeSeriesMetricsImpl.getkafkaTopicOffsets(StormTopologyTimeSeriesMet
ricsImpl.java:86)
        at com.hortonworks.streamline.streams.metrics.storm.topology.StormTopologyMetricsImpl.getkafkaTopicOffsets(StormTopologyMetricsImpl.java:244)
        at com.hortonworks.streamline.streams.metrics.topology.service.TopologyMetricsService.getKafkaTopicOffsets(TopologyMetricsService.java:70)
        at com.hortonworks.streamline.streams.service.MetricsResource.getKafkaTopicOffsets(MetricsResource.java:221)

 	Caused by: java.lang.NullPointerException: null
        at com.hortonworks.streamline.streams.metrics.storm.topology.StormTopologyTimeSeriesMetricsImpl.findKafkaTopicName(StormTopologyTimeSeriesMetricsImpl.java:166)
```

**Comment by omkreddy** [comment]
cc @arunmahadevan  @HeartSaVioR

**Comment by arunmahadevan** [comment]
@HeartSaVioR , Looks like we are looking for the data source in the topology config [here](https://github.com/hortonworks/streamline/blob/master/streams/runners/storm/metrics/src/main/java/com/hortonworks/streamline/streams/metrics/storm/topology/StormTopologyTimeSeriesMetricsImpl.java#L168) and its failing since topology config does not contain the sources.  Should we look for the topic name in the Component (the second argument)? You may also need to copy the the config in the `CatalogToLayoutConverter`. Can you make the necessary changes ? 

You may use the cluster http://172.27.24.138:8080/ for trying out the changes.

**Comment by HeartSaVioR** [comment]
#1118
