### ISSUE TITLE
Notification Sink throws Exception after deployment

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#1140]
When deploying an application with Notification Sink, the following exception gets thrown at runtime.

```
2017-12-28 15:19:23.036 o.a.s.util Thread-5-111-Alert-Speeding-Driver-Alert-executor8 8 ERROR Async loop died!
java.lang.reflect.UndeclaredThrowableException: null
at com.sun.proxy.$Proxy36.open(Unknown Source) ~[?:?]
at com.hortonworks.streamline.streams.notification.service.NotificationServiceImpl.register(NotificationServiceImpl.java:98) ~stormjar.jar:0.6.0.3.1.0.0-420

...

Caused by: java.lang.NoSuchMethodError: com.sun.mail.util.TraceInputStream.<init>(Ljava/io/InputStream;Lcom/sun/mail/util/MailLogger;)V
at com.sun.mail.smtp.SMTPTransport.initStreams(SMTPTransport.java:2109) ~stormjar.jar:0.6.0.3.1.0.0-420
at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2029) ~stormjar.jar:0.6.0.3.1.0.0-420
at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:697) ~stormjar.jar:0.6.0.3.1.0.0-420
at javax.mail.Service.connect(Service.java:313) ~stormjar.jar:0.6.0.3.1.0.0-420
at javax.mail.Service.connect(Service.java:172) ~stormjar.jar:0.6.0.3.1.0.0-420
at javax.mail.Service.connect(Service.java:121) ~stormjar.jar:0.6.0.3.1.0.0-420
at com.hortonworks.streamline.streams.notifiers.EmailNotifier.getEmailTransport(EmailNotifier.java:257) ~stormjar.jar:0.6.0.3.1.0.0-420
```

**Comment by arunmahadevan** [comment]
Fixed via https://github.com/hortonworks/streamline/pull/1141
