### ISSUE TITLE
Streamline classes can not be initialized because of wrong dependencies

### ISSUE THREAD

**Issue by ghajos** [hortonworks/streamline#1277]
After applying the newest source patch on HDF-3.1-maint and HDF-3.1.0.0 unit tests result in:
`Running com.hortonworks.streamline.streams.service.NotificationsResourceTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.014 sec <<< FAILURE! - in com.hortonworks.streamline.streams.service.NotificationsResourceTest
testListNotifications(com.hortonworks.streamline.streams.service.NotificationsResourceTest)  Time elapsed: 0.013 sec  <<< ERROR!
java.lang.ExceptionInInitializerError: null
  at org.apache.log4j.Log4jLoggerFactory.<clinit>(Log4jLoggerFactory.java:50)
  at org.apache.log4j.LogManager.getLogger(LogManager.java:45)
  at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:73)
  at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:284)
  at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:304)
  at com.hortonworks.streamline.streams.security.impl.NoopAuthorizer.<clinit>(NoopAuthorizer.java:30)
  at com.hortonworks.streamline.streams.service.NotificationsResourceTest.<init>(NotificationsResourceTest.java:54)
`
The root cause is that _hive-metastore_ introduce _slf4j-log4j12_ as dependency. Exclude _slf4j-log4j12_ every case when _hive-metastore_ is a dependency solves the problem.

**Comment by HeartSaVioR** [comment]
Closed via #1272
