### ISSUE TITLE
Unable to run Topology !! test case gives NoSuchMethodException

### ISSUE THREAD

**Issue by aditya777hp** [hortonworks/streamline#1332]
I have simple Kafka source and sink but the moment I run it gives NoSuchMethodException, even when I am trying to run the test case it gives the same exception 
I am not able to delete my test cases as well because of the same exception 
Here is the stack Trace
I have used postgresql as the metadata store and checked that the data is being persisted and it is !!
My kafka brokers running fine outside of SAM only in the topology are they not working.

`CERROR  [2019-01-24 17:13:31.185] [dw-130 - POST /api/v1/catalog/topologies/1/actions/testrun] c.h.s.s.s.TopologyTestRunResource -  Got exception: [StorageException] / message [com.hortonworks.registries.storage.exception.StorageException: java.lang.NoSuchMethodException: com.hortonworks.streamline.streams.catalog.TopologyTestRunCaseSource.setOccurrence(java.lang.Long)] / related resource location: [com.hortonworks.streamline.streams.service.TopologyTestRunResource.testRunTopology](TopologyTestRunResource.java:157) 
com.hortonworks.registries.storage.exception.StorageException: com.hortonworks.registries.storage.exception.StorageException: java.lang.NoSuchMethodException: com.hortonworks.streamline.streams.catalog.TopologyTestRunCaseSource.setOccurrence(java.lang.Long)
	at com.hortonworks.registries.storage.impl.jdbc.JdbcStorageManager.find(JdbcStorageManager.java:131)
	at com.hortonworks.registries.storage.impl.jdbc.JdbcStorageManager.find(JdbcStorageManager.java:110)
	at com.hortonworks.streamline.streams.catalog.service.StreamCatalogService.listTopologyTestRunCaseSource(StreamCatalogService.java:2923)
	at com.hortonworks.streamline.streams.service.TopologyTestRunResource.testRunTopology(TopologyTestRunResource.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:34)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:50)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:44)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240)
	at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:396)
	at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:68)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.hortonworks.registries.storage.exception.StorageException: java.lang.NoSuchMethodException: com.hortonworks.streamline.streams.catalog.TopologyTestRunCaseSource.setOccurrence(java.lang.Long)
	at com.hortonworks.registries.storage.catalog.AbstractStorable.fromMap(AbstractStorable.java:93)
	at com.hortonworks.registries.storage.impl.jdbc.provider.sql.factory.AbstractQueryExecutor$QueryExecution.getStorablesFromResultSet(AbstractQueryExecutor.java:480)
	at com.hortonworks.registries.storage.impl.jdbc.provider.sql.factory.AbstractQueryExecutor$QueryExecution.executeQuery(AbstractQueryExecutor.java:363)
	at com.hortonworks.registries.storage.impl.jdbc.provider.sql.factory.AbstractQueryExecutor.executeQuery(AbstractQueryExecutor.java:344)
	at com.hortonworks.registries.storage.impl.jdbc.provider.postgresql.factory.PostgresqlExecutor.select(PostgresqlExecutor.java:121)
	at com.hortonworks.registries.storage.impl.jdbc.JdbcStorageManager.find(JdbcStorageManager.java:128)
	... 61 common frames omitted
Caused by: java.lang.NoSuchMethodException: com.hortonworks.streamline.streams.catalog.TopologyTestRunCaseSource.setOccurrence(java.lang.Long)
	at java.lang.Class.getMethod(Class.java:1786)
	at com.hortonworks.registries.common.util.ReflectionHelper.invokeSetter(ReflectionHelper.java:52)
	at com.hortonworks.registries.storage.catalog.AbstractStorable.fromMap(AbstractStorable.java:90)
	... 66 common frames omitted
`

**Comment by aditya777hp** [comment]
It's an issue with postgres driver make sure to use an appropriate one !!
