### ISSUE TITLE
Test run topology requires write permission for Storm log directory

### ISSUE THREAD

**Issue by HeartSaVioR** [hortonworks/streamline#654]
Storm local cluster also requires write permission to the log directory according to the cluster configuration. This behavior affects test run topology since it utilizes Storm local cluster.

Hence the account which runs streamline should be able to write Storm log directory. Otherwise test run fails.

**Comment by HeartSaVioR** [comment]
```
8261 [Async Localizer] INFO  o.a.s.l.AsyncLocalizer - Extracting resources from jar at /tmp/c47a9a48411311e78ab1fa163ebe64d5.jar to /tmp/befa1e15-1d53-40ed-9674-76977c3c5622/supervisor/tmp/744ba7ba-ef15-4b93-9769-5cbefbaaf78a/
8295 [SLOT_1027] INFO  o.a.s.d.s.Slot - STATE WAITING_FOR_BASIC_LOCALIZATION msInState: 119 -> WAITING_FOR_BLOB_LOCALIZATION msInState: 0
8300 [SLOT_1027] INFO  o.a.s.d.s.Container - Setting up 75e9529a-8f95-49d0-bc05-beff6c39a5cd:2084dba8-c7de-4523-b966-ce6ee70a7de9
8301 [SLOT_1027] ERROR o.a.s.d.s.Slot - Error when processing event
java.io.IOException: Unable to create directory /var/log/storm/workers-artifacts/streamline-3-TestTopology-1-1495693910/1027
        at org.apache.storm.shade.org.apache.commons.io.FileUtils.forceMkdir(FileUtils.java:2472) ~[storm-core-1.1.0.3.0.0.0-362.jar:1.1.0.3.0.0.0-362]
        at org.apache.storm.daemon.supervisor.AdvancedFSOps.forceMkdir(AdvancedFSOps.java:273) ~[storm-core-1.1.0.3.0.0.0-362.jar:1.1.0.3.0.0.0-362]
        at org.apache.storm.daemon.supervisor.Container.setup(Container.java:319) ~[storm-core-1.1.0.3.0.0.0-362.jar:1.1.0.3.0.0.0-362]
        at org.apache.storm.daemon.supervisor.LocalContainerLauncher.launchContainer(LocalContainerLauncher.java:44) ~[storm-core-1.1.0.3.0.0.0-362.jar:1.1.0.3.0.0.0-362]
        at org.apache.storm.daemon.supervisor.Slot.handleWaitingForBlobLocalization(Slot.java:387) ~[storm-core-1.1.0.3.0.0.0-362.jar:1.1.0.3.0.0.0-362]
        at org.apache.storm.daemon.supervisor.Slot.stateMachineStep(Slot.java:275) ~[storm-core-1.1.0.3.0.0.0-362.jar:1.1.0.3.0.0.0-362]
        at org.apache.storm.daemon.supervisor.Slot.run(Slot.java:741) [storm-core-1.1.0.3.0.0.0-362.jar:1.1.0.3.0.0.0-362]
```
