### ISSUE TITLE
SAM Kafka source crashes when target component has parallelism > 1

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#912]
1. Create a Kafka (parallelism=1) -> Aggregate (parallelism=2) -> notification topology (parallelism=2)

2. Deploy

3. Send some events.

Seeing the below exception :-

```
2017-09-13 05:52:03.439 o.a.k.c.c.i.AbstractCoordinator kafka-coordinator-heartbeat-thread | cg11 [DEBUG] Received successful Heartbeat response for group cg11
2017-09-13 05:52:03.705 o.a.s.util Thread-8-11-KAFKA-executor[2 2] [ERROR] Async loop died!
java.lang.IndexOutOfBoundsException: null
	at clojure.lang.PersistentVector.arrayFor(PersistentVector.java:153) ~[clojure-1.7.0.jar:?]
	at clojure.lang.PersistentVector.nth(PersistentVector.java:157) ~[clojure-1.7.0.jar:?]
	at clojure.lang.APersistentVector.get(APersistentVector.java:172) ~[clojure-1.7.0.jar:?]
	at com.hortonworks.streamline.streams.runtime.storm.grouping.FieldsGroupingAsCustomGrouping.chooseTasks(FieldsGroupingAsCustomGrouping.java:57) ~[stormjar.jar:0.1.0-SNAPSHOT]
	at org.apache.storm.daemon.executor$mk_custom_grouper$fn__4869.invoke(executor.clj:63) ~[storm-core-1.1.0.3.0.1.0-43.jar:1.1.0.3.0.1.0-43]
	at org.apache.storm.daemon.task$mk_tasks_fn$fn__4820.invoke(task.clj:157) ~[storm-core-1.1.0.3.0.1.0-43.jar:1.1.0.3.0.1.0-43]
	at org.apache.storm.daemon.executor$fn__5136$fn__5151$send_spout_msg__5157.invoke(executor.clj:564) ~[storm-core-1.1.0.3.0.1.0-43.jar:1.1.0.3.0.1.0-43]
	at org.apache.storm.daemon.executor$fn__5136$fn$reify__5167.emit(executor.clj:612) ~[storm-core-1.1.0.3.0.1.0-43.jar:1.1.0.3.0.1.0-43]
	at org.apache.storm.spout.SpoutOutputCollector.emit(SpoutOutputCollector.java:50) ~[storm-core-1.1.0.3.0.1.0-43.jar:1.1.0.3.0.1.0-43]
	at org.apache.storm.kafka.spout.KafkaSpout.emitTupleIfNotEmitted(KafkaSpout.java:356) ~[dep-org.apache.storm-storm-kafka-client-jar-1.1.0.3.0.0.0-453.jar.1502100575000:1.1.0.3.0.0.0-453]
	at org.apache.storm.kafka.spout.KafkaSpout.emit(KafkaSpout.java:316) ~[dep-org.apache.storm-storm-kafka-client-jar-1.1.0.3.0.0.0-453.jar.1502100575000:1.1.0.3.0.0.0-453]
	at org.apache.storm.kafka.spout.KafkaSpout.nextTuple(KafkaSpout.java:236) ~[dep-org.apache.storm-storm-kafka-client-jar-1.1.0.3.0.0.0-453.jar.1502100575000:1.1.0.3.0.0.0-453]
	at org.apache.storm.daemon.executor$fn__5136$fn__5151$fn__5182.invoke(executor.clj:647) ~[storm-core-1.1.0.3.0.1.0-43.jar:1.1.0.3.0.1.0-43]
	at org.apache.storm.util$async_loop$fn__553.invoke(util.clj:484) [storm-core-1.1.0.3.0.1.0-43.jar:1.1.0.3.0.1.0-43]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
2017-09-13 05:52:03.720 o.a.s.d.executor Thread-8-11-KAFKA-executor[2 2] [ERROR] 
```

**Comment by priyank5485** [comment]
Fixed in https://github.com/hortonworks/streamline/issues/942
